language: python

python:
  - 3.6

env:
  - DJANGO=2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=cardholder.settings
  - export PYTHONPATH=$HOME/builds/cardholder/server-side
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
 

script:
  - python manage.py test
