language: python

python:
  - 3.6

services:
  - mysql

addons:
  mariadb: '10.0'

env:
  - DJANGO=2.2

before_script:
  - sudo mysql -e 'CREATE DATABASE test_cardholderdb CHARACTER SET UTF8;CREATE USER cardholderuser@localhost IDENTIFIED BY "1234";GRANT ALL PRIVILEGES ON test_cardholderdb.* TO cardholderuser@localhost;FLUSH PRIVILEGES;'

before_install:
  - sudo apt-get install -y libmariadbclient-dev 
  - export DJANGO_SETTINGS_MODULE=cardholder.settings
  - export PYTHONPATH=$HOME/builds/cardholder/server-side
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
 

script:
  - python manage.py test
