language: python
python:
- 3.6
env:
 -DJANGO=2.2
 
  secure: v6VY1XsAoCE2pKzYcjMcRgUmfmltG0Y+KElK0sAJfGBWfplhJ0jI/TbjOXTdoQsEgNXKzOb1QeeCYG72Jz/L36d/Ygf8lKuzjERDy497V6LdADKjNag2z1qd8CJYxXCsTI8bbGpxXaVzmILZIqnufr77r4yAWZ6hCNOLdUEYj1lSCIY+mVWGLN8BJkv+FLhutUr6XrcRyltO2VNz+pNLTq4aiQQeKG/+lv5wfAaAwNTNeleTwSGsOf7ZcziRlr8UdgB0Dd3kkfozVQpPRlkAgNM4eAkNM7EJqUMYp3PTwkZDT6fhYlfmT25xSE+2OTaK3t1PRrebT2RdkyHv6wYigPvsGlUJ6T0VvKzx/0J8Y9tb7RCNRrBOC+JxIJBa/gtYFc8n3xLTxreA83AZoJVKsvCZy7FiuwZ73FGBmRBsZKdmn4ogBvhhS4XDJaAwlekdIbqvXH4m86ltQ4SxYwahZOM6P70lBo2rXgK09u2N1TS4Z08/CI6CoiHBQ5aEn4xa3fJfQ8BidfFAQ0pY/I9BD69Rttub9EDpGiRAyL3yfXZG0saz7wkhFSWfGJWItzTVOP+iouGRnXLefd0MjZF15iaOyuocTLW7gwEP/y2Td+iK7H8uZ83KvwC5FqqzFlt5++brZcgRDzWOWqlg3rT1pDOtHnAQPHHd4TYqSI9htQo=
 
before_install:
- export DJANGO_SETTINGS_MODULE=cardholder.settings
- export PYTHONPATH=$HOME/builds/cardholder/server-side
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
script:
- python manage.py test
